version: '2'
services:

  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://localhost:2379

  receiver:
    build: application
    depends_on:
      - etcd
    ports:
      - 10000:8080
    environment:
      SPRING_PROFILES_ACTIVE: receiver
      WEB_ENVIRONMENT: 'true'

  processor:
    build: application
    depends_on:
      - etcd
    environment:
      SPRING_PROFILES_ACTIVE: processor
      WEB_ENVIRONMENT: 'false'

  transmitter:
    build: application
    depends_on:
      - etcd
    environment:
      SPRING_PROFILES_ACTIVE: transmitter
      WEB_ENVIRONMENT: 'true'
    ports:
      - 20000:8080